### ISSUE TITLE
Add policies and service for bind-mounting files

### ISSUE THREAD

**Issue by slifox** [phhusson/super-bootimg#3]
These permissions are used for bind mounting files -- in particular, for mounting a file over /system/etc/hosts

For bind mounting /data/local/tmp/hosts to /system/etc/hosts on boot from init.rc:

```
allow toolbox system_file file "mounton"
allow toolbox toolbox capability "sys_admin"
allow toolbox shell_data_file dir "read search getattr open"
allow toolbox shell_data_file file "read getattr open ioctl"
```

This mount can be accomplished on boot by adding this to init.rc:

```
service hosts_file /system/bin/mount -o bind /data/local/tmp/hosts /system/etc/hosts
        user root
        class late_start
        oneshot
```

**Comment by lbdroid** [comment]
Those permissions look a little too general to be safely added, since they also would allow the toolbox domain to mount _other_ files over the system, even after boot is completed.

**Comment by phhusson** [comment]
toolbox.te:neverallow { domain -init } toolbox:process transition;
Sounds safe enough.

**Comment by lbdroid** [comment]
How about for things that are already in the toolbox domain?

**Comment by phhusson** [comment]
I don't really see the problem
Only init can start stuff in toolbox domain, and toolbox being able to change things in /system is not really dangerous since it already is in /system
And I doubt there is any daemon in toolbox (no process in toolbox context running on N4 5.1, N9 6.0, CAF 6.0, MTK 5.1)

**Comment by phhusson** [comment]
You're still seeing anything that could compromise the system?

**Comment by lbdroid** [comment]
I honestly haven't had a chance to look at it in detail. Long day. I should be able to find some time tomorrow to take a better look at all the implications.

**Comment by phhusson** [comment]
su --bind implemented in su_daemon
