### ISSUE TITLE
getprop: Command not found

### ISSUE THREAD

**Issue by retsifp** [phhusson/super-bootimg#32]
I'm getting this on my debian testing system:
`super-bootimg/scripts//bootimg.sh: Zeile 227: getprop: Kommando nicht gefunden.`

It's something about samsung phones, so I think it's not a major issue and the build works.

**Comment by phhusson** [comment]
First thing to note is that the whole script is run with "set -e", so any "uncatched" error will prevent the script from generating a boot.img.
Now, in this precise case, the feature inside the if is purely cosmetic. (the bootloader displays a red warning on boot without it)
So even on Samsung devices, this is not a problem.
