### ISSUE TITLE
hidesu for x86

### ISSUE THREAD

**Issue by ameel** [phhusson/super-bootimg#37]
by way of background, I built latest git. Needed to modify the install script to work for Zenfone 2 (x86). SuperUser works fine. All files appear to have been placed properly (including hidesu). However, SafetyNet doesn't pass anymore, which makes me think hidesu isn't working as intended.

In [jni/hidesu.c](https://github.com/phhusson/super-bootimg/blob/master/jni/hidesu.c#L27), there's comment `//TODO: Fix non arm platforms`. What needs to be fixed? I'm keen to fix or test for x86.

**Comment by phhusson** [comment]
Should be fixed by https://github.com/phhusson/super-bootimg/commit/018fd3a0ea396017994e19a0ef1bcd5fe44360b9
